language: csharp
solution: Dawn of Light.sln
sudo: false # Use container-based infrastructure

env:
  matrix:
   - XBUILD_TARGET=Debug
   - XBUILD_TARGET=Release

install:
 - travis_retry nuget restore DOLServer/packages.config -SolutionDirectory ./
 - travis_retry nuget install NUnit.Console -OutputDirectory test -ExcludeVersion
script:
 - MONO_IOMAP=case xbuild /p:Configuration=$XBUILD_TARGET "Dawn of Light.sln"
 - mkdir -p ./build/UnitTests/$XBUILD_TARGET/config
 - sed -e 's/type\=\"log4net\.Appender\.ColoredConsoleAppender\"/type\=\"log4net\.Appender\.ConsoleAppender\"/' ./GameServer/config/logconfig.xml > ./build/UnitTests/$XBUILD_TARGET/config/logconfig.xml
 - LANG=en_US.CP1252 mono ./test/NUnit.ConsoleRunner/tools/nunit3-console.exe ./build/UnitTests/$XBUILD_TARGET/lib/UnitTests.dll
