version: 1.9.7.{build}

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

configuration:
- Debug
- Release

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

cache: packages -> **\packages.config

before_build:
- |-
  git submodule update --init --recursive
  nuget restore

build_script:
- |-
  msbuild -p:Configuration=%CONFIGURATION% -v:minimal "Dawn of Light.sln"

after_build:
- |-
  7z a -tzip DOLServer_net45_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\*
  xcopy %APPVEYOR_BUILD_FOLDER%\sharedModules\SQLite\managedOnly\System.Data.SQLite.dll %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\lib /y /s /q /i
  del %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\lib\x64 /F /S /Q
  del %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\lib\x86 /F /S /Q
  7z a -tzip DOLServer_linux_net45_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\*
  7z a -tzip DOLServer_UnitTests_net45_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\build\Tests\%CONFIGURATION%\*

test_script:
  - nunit3-console ".\build\Tests\%CONFIGURATION%\lib\Tests.dll" --where "namespace =~ 'DOL.UnitTests' and category != 'Explicit'" --result=myresults.xml;format=AppVeyor
  - nunit3-console ".\build\Tests\%CONFIGURATION%\lib\Tests.dll" --where "namespace =~ 'DOL.Integration' and category != 'Explicit'" --result=myresults.xml;format=AppVeyor

artifacts:

- path: '*.zip'
  name: Release

deploy:
- provider: GitHub
  auth_token:
    secure: Z7WRKyMZZ4esjZvQ3PtzvUYh+2u+Sav9BFncK6j9PDr/9PZ8I46ZglREI2i6Mj0T
  artifact: Release
